//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcExpense.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialExpense
    {
        public long Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Sequence { get; set; }
        public double Price { get; set; }
        public long ConsumerId { get; set; }
        public string Description { get; set; }
    
        public virtual Consumer Consumer { get; set; }
    }
}
